### ISSUE TITLE
请问下顺序执行网络请求

### ISSUE THREAD

**Issue by ixxxxxx** [AnyLifeZLB/Android-MVP-Rxjava2#20]
您好，用了您的封装的网络框架，因为里面有Rx，所以一直用的都是异步（也有可能我理解有误）。
但是现在是需要发送图片后获取服务器返回的id，然后在把多个图片id发送给服务器。
现在两个请求都是用toMainThread，但是由于发送图片时间过长，经常是后一个请求先执行。
请问怎么让第一个请求完成后才执行第二个？
ps：第一个请求只能发送一张照片，所以我用了for循环执行多个请求。

**Comment by AnyLifeZLB** [comment]
@CheckReturnValue
@SchedulerSupport(SchedulerSupport.NONE)
public static <T, R> Observable<R> zip(Iterable<? extends ObservableSource<? extends T>> sources, Function<? super Object[], ? extends R> zipper) {
    ObjectHelper.requireNonNull(zipper, "zipper is null");
    ObjectHelper.requireNonNull(sources, "sources is null");
    return RxJavaPlugins.onAssembly(new ObservableZip<T, R>(null, sources, zipper, bufferSize(), false));
}

哎，竟然不会用。。。

**Comment by ixxxxxx** [comment]
感谢，刚看到。我试一下。

> 意思就是要等N个网络请求结束后再把那N个请求返回的结果统一一起发给服务器，对吗？

**Comment by ixxxxxx** [comment]
后台可以一次性上传多个文件，这样我就在onSuccess里面直接把ids[]上传上去了。
不过这个Rx的Zip等明后天有空再深研究下，感谢博主指点。
